language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

install:
  - npm run client:init

before_script:
  - npm run client:build
  - sleep 15

script:
  - npm test

on:
  branch: master

after_success:
  - npm run coverage
  