module.exports = [
  {
    id: 0,
    cardTitle: 'Directory',
    cardImage: null,
    description: 'Lists local organisations and services following research.',
    difficulty: 'TBA',
    category: 'Finding',
    requires: 'Database',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 1,
    cardTitle: 'Location Map',
    description: 'Shows favourite local places and useful organisations.',
    cardImage: null,
    difficulty: 'TBA',
    category: 'Finding',
    requires: 'Database',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 2,
    cardTitle: 'Network map',
    description:
      "Shows who knows who, and how groups and projects connect, with information about people's needs, skills and interests.",
    cardImage: null,
    difficulty: 'TBA',
    category: ['Finding', 'Sharing', 'Collaborating'],
    requires: 'Database',
    use: 'TBA',
    resourcePoints: 3,
  },
  {
    id: 3,
    cardTitle: 'Story map',
    description:
      'Text, images, audio and video enliven a location map and can be used to create exploration trails.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Finding'],
    requires: 'Database',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 4,
    cardTitle: 'Database',
    description:
      'Spreadsheet to support maps and communications manages information effectively.  Needs survey tool.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Managing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 5,
    cardTitle: 'Research and survey tool',
    description:
      'Allows you to collect data from people and organisations for maps and communications.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Managing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 6,
    cardTitle: 'Facebook page and group',
    description:
      'The page can provide the public face, with a group that is open or closed. Many other tools for connecting and organising as well.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Finding', 'Sharing', 'Collaborating'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 7,
    cardTitle: 'Email newsletter',
    description: 'Allows a group to send updates to peoples mailboxes.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing'],
    requires: 'Database',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 8,
    cardTitle: 'Email group',
    description:
      'Enables many-to-many communications by sending emails to and from a central address.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing', 'Collaborating'],
    requires: 'Database',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 9,
    cardTitle: 'Event scheduling',
    description:
      'Avoids lengthy email exchanges by offering people an online system to choose dates and times.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Managing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 10,
    cardTitle: 'Event organising',
    description:
      'Enables online registration for events, with emails for reminders and updates.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Managing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 11,
    cardTitle: 'Events calendar',
    description: 'Provides a shared calendar of community events.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Finding', 'Sharing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 12,
    cardTitle: 'News and information site',
    description:
      'Provides update posts and information pages for the community, with scope to add other tools.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Finding', 'Sharing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 3,
  },
  {
    id: 13,
    cardTitle: 'Website',
    description: 'Provides an online presence for a group or organisation.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 14,
    cardTitle: 'Forum',
    description:
      'Offers a facilitated update and discussion space for the community.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing', 'Collaborating'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 15,
    cardTitle: 'Ideas platform',
    description:
      'A space to solicit , discuss and rank ideas for a better Slipham.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Collaborating'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 16,
    cardTitle: 'Video Conferencing',
    description:
      'System like Zoom or Skype offers webinars and online group events.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Collaborating', 'Sharing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 17,
    cardTitle: 'Collaborative document system',
    description:
      'A system like Google docs or Quip enables a group to work online on the same pages.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Collaborating'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 18,
    cardTitle: 'Aggregators',
    description:
      'Social media content from a range of sources made easily accessible.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Finding', 'Sharing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
  {
    id: 19,
    cardTitle: 'Private messaging',
    description: 'WhatsApp and similar messaging systems used by groups.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing', 'Collaborating'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 19,
    cardTitle: 'Social media',
    description:
      'Instagram, Twitter and other social media tools are used by individuals and groups.',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing', 'Collaborating'],
    requires: '',
    use: 'TBA',
    resourcePoints: 1,
  },
  {
    id: 20,
    cardTitle: 'Video storytelling',
    description:
      'Connectors use smart phones to create audio and video stories',
    cardImage: null,
    difficulty: 'TBA',
    category: ['Sharing'],
    requires: '',
    use: 'TBA',
    resourcePoints: 2,
  },
];
